version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres-accounting
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data