"""modified file model

Revision ID: cf4bd80eba96
Revises: f911c9240c26
Create Date: 2024-06-04 14:13:23.171653

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cf4bd80eba96"
down_revision: Union[str, None] = "f911c9240c26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("year", sa.Integer(), nullable=False))
    op.add_column("files", sa.Column("month", sa.Integer(), nullable=False))
    op.add_column(
        "files",
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "expiration_date")
    op.drop_column("files", "month")
    op.drop_column("files", "year")
    # ### end Alembic commands ###
